name: Test Action

on: [push]

jobs:
    test:
      run-on: ubuntu-latest
      steps:
        -name: 23ds2000041@ds.study.iitm.ac.in
        run:  echo "step with email in name"

          -name:Another Step
           run:echo "Hello, World!"
